# Generated by Django 5.2.17 on 2026-09-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_sitesettings_why_choose_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='listingphoto',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Website Settings', 'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AlterModelOptions(
            name='smtpsettings',
            options={'verbose_name': 'SMTP Email Settings', 'verbose_name_plural': 'SMTP Email Settings'},
        ),
        migrations.AlterModelOptions(
            name='tourrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='realestate__status_72a59c_idx',
            old_name='realestate_l_status_9efae2_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='realestate__bedroom_c0b80d_idx',
            old_name='realestate_l_bedroom_6e2d95_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='map_url',
            field=models.URLField(blank=True, help_text='Optional custom Google Maps or map URL. Address remains the primary location.'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(upload_to='listings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional alternative. Uploading a file is the primary method.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Optional. Leave blank if you do not want an address in the footer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='self_tour_phone',
            field=models.CharField(blank=True, help_text='Phone number used after a Schedule Self Tour form is submitted.', max_length=40),
        ),
    ]
