# Generated by Django 5.2.17 on 2026-09-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_feature_options_alter_fee_options_and_more'),
        ('realestate', '0003_alter_listingphoto_image'),
    ]

    operations = [
    ]
