# Generated by Django 5.2.17 on 2026-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_merge_20260928_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/'),
        ),
    ]
